name: peak_it_2024_app
description: "Application made at PeakIT 2024 Hackathon"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.2
  smooth_corner: ^1.1.0
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.1
  retrofit_generator: ^9.1.2
  widgetbook: ^3.9.0
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Black.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Bold.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Heavy.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Light.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Medium.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Regular.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Semibold.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Thin.ttf
        - asset: assets/fonts/sf_pro_rounded/SF-Pro-Rounded-Ultralight.ttf
    - family: SheruPro
      fonts:
        - asset: assets/fonts/sheru_pro/sheru_pro.otf