name: peak_it_2024_app
description: "Application made at PeakIT 2024 Hackathon"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auto_route: ^9.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true
